version: '3.3'

services:
  dev_node: &dev_node
    image: node:8
    volumes:
      - "../../:/usr/src/app"
    working_dir: /usr/src/app

  node: &node
    <<: *dev_node
    entrypoint: ["node"]
    command: ["--help"]
    expose:
      - "3000"
    ports:
      - "3000:3000"

  npm:
    <<: *dev_node
    entrypoint: ["npm"]
    command: ["--help"]

  web:
    container_name: "http_server"
    image: nginx:1.13-alpine
    ports:  
      - "8888:80"
    expose:
      - "80"
    volumes:
      - "../../public:/usr/share/nginx/html:ro"
